### ISSUE TITLE
Problem usage of .mesh files from GMSH

### ISSUE THREAD

**Issue by PhilippIce** [ISCDtoolbox/Mshdist#8]
Hello everybody, 
I was starting to use the mshdist program together with gmsh. However, with the standard .mesh files from gmsh I am running into some problems. 

I think, this is due to the dimensions. GMSH exports the .mesh files with dimension 3, however, apparently mshdist cannot handle that. 

I attached some examples to reproduce this. You can run it with `mshdist outer3.mesh inner3.mesh` 

This leads to the following error:
```
 -- PHASE 2 : DISTANCING
  ** Initialization
     distance
     Building circumcircle table...done. 
  ** Sign identification
     1 connected component(s)
  ## Problem in sign function
  -- PHASE 2 COMPLETED.     0.004s
```
When I manually delete the z component and change the dimension to 2, everything works fine again. 

Is there a flag or something I can set 

Thanks a lot for your help! 

Philipp
[meshes.tar.gz](https://github.com/ISCDtoolbox/Mshdist/files/8581613/meshes.tar.gz)

**Comment by Algiane** [comment]
Hi,

I don't think that mshdist provides a way to ignore the z-component of a mesh but you can use [Mmg](https://github.com/MmgTools/mmg) to convert 2D gmsh .mesh files into 2D Medit .mesh file (used by mshdist).

The compilation and command line of Mmg are pretty close to Mshdist ones as both tools have the same historical developers.

You can get help with Mmg2d using: `mmg2d_O3 -h`.

The command line to convert your gmsh file into a Medit one without modifying it is the following:
`
mmg2d_O3 -3dMedit 3 -noinsert -noswap -nomove 3Dmesh.mesh 3Dmesh.mesh
`

The `-noinsert -noswap -nomove` options forbid the remeshing. You can also provide a .msh file to Mmg and directly convert it into a .mesh one (in this case the `-3dMedit` option is useless).

In all cases, even without remeshing your mesh, Mmg will analyze it so it can add boundary edges, corners or things like that in your .mesh file but it should not be a problem for mshdist.

I hope that it helps!

Best regards,
Algiane

**Comment by PhilippIce** [comment]
Hi, 
Thank you very much. That was very helpful. I will be using this! 

Best regards, 

Philipp
